### PR TITLE
API migration initiator

### PR DESCRIPTION
**Pull request by tfukushima**
This patch updates the copyright notifications in the headers of files.
The following patches added by Midokura should use the same copyright
statement as follow:

  Copyright (C) 2014 Midokura SARL.

Signed-off-by: Taku Fukushima tfukushima@midokura.com

### CODE REVIEW

**Comment by tfukushima** [comment]
This is just a test flight indicating I start with this patch.

**Comment by tfukushima** [comment]
@ryu25ish @jdevesa I added the initial trial. It's still in progress and we need to call RPCs in it.

**Comment by tfukushima** [comment]
@jdevesa :scream: Thanks for letting me know.

**Comment by tfukushima** [comment]
@ryu25ish @joemido @jdevesa: I introduced the initial version of the decorators for the API handler mixins in 340ff91 and the extensions in ~~170b472~~ 754dc69
. Could you take a look at them?

**Comment by devvesa** [comment]
Hi Taku, I think we should take as a common behaviour to use a single commit per pull request. Are you agree?

**Comment by ryu25ish** [comment]
I don't think we need to enforce a single commit per pull request insofar as it is a group of closely related commits.   But in this case, especially since this work is still considered WIP, a commit like updating copyrights should be separated into a different pull request.

**Comment by tfukushima** [comment]
I cleaned the patches up to use the generated methods automatically by the decorators. I also fixed issues decorators didn't return the wrapped classes/functions.

@jdevesa If we enforce a pull request per patch, when we have the dependency between patches we would be blocked until the first patch is merged. On the other hand, I agree that it's better to separate patches in the fine grained units.

As a trial I put the aggregated series of patches here and the individual no-dependency patches on #8 and #9. The last of three patch depends on both so I can't create a pull request until both of them are merged.

**Pull request closed without merging**
